workflows:
  ios-project-debug:
    name: iOS debug
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "MyListGamesExpert.xcworkspace" # workspace kamu
        XCODE_SCHEME: "MyListGamesExpert" # nama scheme kamu
    scripts:
      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build debug app
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=16.1' \
            clean build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app

    publishing:
      email:
        recipients:
          - alief.ahmadazies@gmail.com
